language: julia
sudo: true

os:
    - linux
    - osx
    - windows
julia:
    - 1.0
    - 1.3
    - nightly
notifications:
    email: false
addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-0   # needed to support the pre-JLL packages
matrix:
  allow_failures:
    - julia: nightly
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    # - if [[ `uname` = "Linux" ]]; then TESTCMD='xvfb-run --auto-servernum --server-num=99 --server-args="-screen 99 640x480x24" julia'; else TESTCMD='julia'; fi
    - if [[ `uname` = "Linux" ]]; then TESTCMD='xvfb-run julia'; else TESTCMD='julia'; fi
    - $TESTCMD -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg, GtkReactive; cd(dirname(dirname(pathof(GtkReactive)))); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
